## Generated by fluent_migrate.py from the pre-20250330 hard-coded chrome strings
tdo-aircraft-tooltip = Aircraft
tdo-apm = APM
tdo-army = Army
tdo-army-value = Army Value
tdo-asset-browser = Asset Browser
tdo-assets = Assets
tdo-attack-anything-stance-tooltip = Attack Anything Stance
tdo-attack-move-tooltip = Attack Move
tdo-audio-muted = Audio Muted
tdo-back = Back
tdo-battlefield-news = Battlefield News
tdo-bldg-killed = Bldg Killed
tdo-bldg-lost = Bldg Lost
tdo-buildings-tooltip = Buildings
tdo-cash = Cash
tdo-communication-tooltip = Communication
tdo-credits = Credits
tdo-deaths = Deaths
tdo-debug-menu-tooltip = Debug Menu
tdo-defend-stance-tooltip = Defend Stance
tdo-deploy-tooltip = Deploy
tdo-destroyed = Destroyed
tdo-download-the-latest-version-from-www-c5f8e6 = Download the latest version from www.openra.net
tdo-earned = Earned
tdo-extras = Extras
tdo-fast-speed-tooltip = Fast speed
tdo-force-attack-tooltip = Force Attack
tdo-force-move-tooltip = Force Move
tdo-guard-tooltip = Guard
tdo-harvesters = Harvesters
tdo-hold-fire-stance-tooltip = Hold Fire Stance
tdo-income = Income
tdo-infantry-tooltip = Infantry
tdo-kills = Kills
tdo-load = Load
tdo-load-map = Load Map
tdo-loading-saved-game = Loading Saved Game
tdo-lost = Lost
tdo-manage-content = Manage Content
tdo-map-editor = Map Editor
tdo-max = MAX
tdo-maximum-speed-tooltip = Maximum speed
tdo-missions = Missions
tdo-multiplayer = Multiplayer
tdo-music = Music
tdo-naval-tooltip = Naval
tdo-new-map = New Map
tdo-oil-derricks = Oil Derricks
tdo-on-hold = ON HOLD
tdo-options = Options
tdo-options-tooltip = Options
tdo-pause-tooltip = Pause
tdo-place-beacon-tooltip = Place Beacon
tdo-play-tooltip = Play
tdo-player = Player
tdo-power = Power
tdo-press-escape-to-cancel-loading-and-36c471 = Press Escape to cancel loading and return to the main menu
tdo-production = Production
tdo-quit = Quit
tdo-ready = READY
tdo-regular-speed-tooltip = Regular speed
tdo-repair-tooltip = Repair
tdo-replays = Replays
tdo-return-fire-stance-tooltip = Return Fire Stance
tdo-scatter-tooltip = Scatter
tdo-score = Score
tdo-scroll-down-tooltip = Scroll down
tdo-scroll-up-tooltip = Scroll up
tdo-selected-units-will-attack-the-targeted-154c87-desc =
    Selected units will attack the targeted unit or location
     - Default activity for the target is suppressed
     - Allows targeting of own or ally forces
     - Long-range artillery units will always target the
       location, ignoring units and buildings

    Left-click icon then right-click on target.
    Hold <(Ctrl)> to activate temporarily while commanding units.
tdo-selected-units-will-follow-the-targeted-ff0060-desc =
    Selected units will follow the targeted unit.

    Left-click icon then right-click on target unit.
tdo-selected-units-will-move-to-the-9ece26-desc =
    Selected units will move to the desired location
    and attack any enemies they encounter en route.

    Hold <(Ctrl)> while targeting to order an Assault Move
    that attacks any units or structures encountered en route.

    Left-click icon then right-click on target location.
tdo-selected-units-will-move-to-the-f6746f-desc =
    Selected units will move to the desired location
     - Default activity for the target is suppressed
     - Vehicles will attempt to crush enemies at the target location
     - Helicopters will land at the target location
     - Chrono Tanks will teleport towards the target location

    Left-click icon then right-click on target.
    Hold <(Alt)> to activate temporarily while commanding units.
tdo-selected-units-will-perform-their-default-f04161-desc =
    Selected units will perform their default deploy activity
     - MCVs will unpack into a Construction Yard
     - Construction Yards will re-pack into a MCV
     - Transports will unload their passengers
     - Demolition Trucks and MAD Tanks will self-destruct
     - Minelayers will deploy a mine
     - Aircraft will return to base

    Acts immediately on selected units.
tdo-selected-units-will-stop-their-current-9992a4-desc =
    Selected units will stop their current activity.

    Acts immediately on selected units.
tdo-selected-units-will-stop-their-current-da9761-desc =
    Selected units will stop their current activity
    and move to a nearby location.

    Acts immediately on selected units.
tdo-sell-tooltip = Sell
tdo-set-the-selected-units-to-attack-631a33-desc =
    Set the selected units to Attack Anything stance:
     - Units will attack enemy units and structures on sight
     - Units will pursue attackers across the battlefield
tdo-set-the-selected-units-to-defend-347c06-desc =
    Set the selected units to Defend stance:
     - Units will attack enemy units on sight
     - Units will not move or pursue enemies
tdo-set-the-selected-units-to-hold-b3ff86-desc =
    Set the selected units to Hold Fire stance:
     - Units will not fire upon enemies
     - Units will not move or pursue enemies
tdo-set-the-selected-units-to-return-aba05d-desc =
    Set the selected units to Return Fire stance:
     - Units will retaliate against enemies that attack them
     - Units will not move or pursue enemies
tdo-settings = Settings
tdo-singleplayer = Singleplayer
tdo-skirmish = Skirmish
tdo-slow-speed-tooltip = Slow speed
tdo-spent = Spent
tdo-stop-tooltip = Stop
tdo-support-powers = Support Powers
tdo-tiberian-dawn = Tiberian Dawn
tdo-units-killed = Units Killed
tdo-units-lost = Units Lost
tdo-use-waypoint-mode-to-give-multiple-61425b-desc =
    Use Waypoint Mode to give multiple linking commands
    to the selected units. Units will execute the commands
    immediately upon receiving them.

    Left-click icon then give commands in the game world.
    Hold <(Shift)> to activate temporarily while commanding units.
tdo-vehicles-tooltip = Vehicles
tdo-waypoint-mode-tooltip = Waypoint Mode
tdo-you-are-running-an-outdated-version-fdd212 = You are running an outdated version of OpenRA.
